/**
 * Builds every icon asset from one source of truth: public/icon-app.svg.
 *
 *   node scripts/generate-icons.mjs
 *
 * Outputs
 *   public/icon-app-maskable.svg   derived, full-bleed, mark inside the safe zone
 *   public/icon-180.png            apple-touch-icon
 *   public/icon-192.png            manifest
 *   public/icon-app-512.png        manifest + Organization JSON-LD logo
 *   public/icon-maskable-512.png   manifest, purpose="maskable"
 *
 * Why this exists: these PNGs used to be produced by hand outside the repo, and
 * every one of them had been committed with a corrupted header — the leading
 * 0x89 byte replaced by the UTF-8 replacement character (ef bf bd) — so no icon
 * or share image actually rendered anywhere. Generating them from the SVG keeps
 * them in step with the brand and makes that corruption impossible to
 * reintroduce quietly: the script verifies the signature of every file it
 * writes and exits non-zero if one is wrong.
 *
 * Requires the Chromium that Playwright installs for this project
 * (`npx playwright install chromium`, which postinstall already runs).
 */
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pub = path.join(root, 'public');
const SOURCE = 'icon-app.svg';
const MASKABLE = 'icon-app-maskable.svg';

/**
 * Android masks a maskable icon to a circle whose diameter is 80% of the canvas
 * (409.6px of 512). The mark measures 259.8 x 286.8 before the outer scale, so
 * its bounding-box diagonal is 386.9 x scale; at the 1.18 used for the rounded
 * tile that is 456px and the corners would be cropped. 1.05 puts the diagonal at
 * 406px, just inside the safe circle.
 */
const MASKABLE_SCALE = '1.05';
const TILE_SCALE = '1.18';

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

/** Derive the full-bleed maskable variant from the tile artwork. */
function buildMaskable(svg) {
  const roundedTile = 'id="tile-rect" width="512" height="512" rx="120"';
  const markScale = `id="mark" transform="translate(256 256) scale(${TILE_SCALE})`;
  if (!svg.includes(roundedTile)) throw new Error(`${SOURCE}: #tile-rect marker not found`);
  if (!svg.includes(markScale)) throw new Error(`${SOURCE}: #mark scale(${TILE_SCALE}) marker not found`);

  return svg
    // no rounded corners: the OS supplies the shape, brand colour must reach every edge
    .replace(roundedTile, 'id="tile-rect" width="512" height="512" rx="0"')
    .replace(markScale, `id="mark" transform="translate(256 256) scale(${MASKABLE_SCALE})`)
    .replace(
      '<title>RoamJelly</title>',
      '<title>RoamJelly</title>\n  <!-- GENERATED by scripts/generate-icons.mjs from icon-app.svg — do not edit. -->'
    );
}

async function rasterise(browser, svg, outPath, size) {
  const page = await browser.newPage({
    viewport: { width: size, height: size },
    deviceScaleFactor: 1,
  });
  // The icons are opaque tiles, so there is no transparent padding to preserve.
  await page.setContent(
    `<style>html,body{margin:0;padding:0}` +
      `svg{display:block;width:${size}px;height:${size}px}</style>${svg}`
  );
  await page.screenshot({ path: outPath });
  await page.close();
}

function signatureOk(file) {
  const head = Buffer.alloc(8);
  const fd = fs.openSync(file, 'r');
  fs.readSync(fd, head, 0, 8, 0);
  fs.closeSync(fd);
  return head.equals(PNG_SIGNATURE);
}

async function main() {
  const svg = fs.readFileSync(path.join(pub, SOURCE), 'utf8');

  const maskableSvg = buildMaskable(svg);
  fs.writeFileSync(path.join(pub, MASKABLE), maskableSvg);
  console.log(`ok   ${MASKABLE.padEnd(26)}  derived from ${SOURCE}`);

  const jobs = [
    [svg, 'icon-180.png', 180],
    [svg, 'icon-192.png', 192],
    [svg, 'icon-app-512.png', 512],
    [maskableSvg, 'icon-maskable-512.png', 512],
  ];

  const browser = await chromium.launch();
  try {
    for (const [source, name, size] of jobs) {
      await rasterise(browser, source, path.join(pub, name), size);
    }
  } finally {
    await browser.close();
  }

  let bad = 0;
  for (const [, name, size] of jobs) {
    const file = path.join(pub, name);
    const ok = signatureOk(file);
    if (!ok) bad++;
    const kb = (fs.statSync(file).size / 1024).toFixed(1);
    console.log(`${ok ? 'ok  ' : 'BAD '} ${name.padEnd(26)} ${String(size).padStart(3)}px  ${kb.padStart(7)} KB`);
  }

  if (bad) {
    console.error(`\n${bad} file(s) written with an invalid PNG signature`);
    process.exitCode = 1;
  } else {
    console.log(`\n${jobs.length} PNGs + 1 SVG written, all PNG signatures valid`);
  }
}

await main();
